name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        mobx-version: ['6.3.4', '7']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Install MobX ${{ matrix.mobx-version }}
        run: npm install --no-save --legacy-peer-deps mobx@${{ matrix.mobx-version }}

      - name: Test
        run: npm test
